export enum TaskImpact {
  HIGH_IMPACT_HIGH_EFFORT = 'HIGH_IMPACT_HIGH_EFFORT',
  HIGH_IMPACT_LOW_EFFORT = 'HIGH_IMPACT_LOW_EFFORT',
  LOW_IMPACT_HIGH_EFFORT = 'LOW_IMPACT_HIGH_EFFORT',
  LOW_IMPACT_LOW_EFFORT = 'LOW_IMPACT_LOW_EFFORT',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
}
