export enum TaskImpact {
  HIGH_IMPACT_HIGH_EFFORT = 'HIGH_IMPACT_HIGH_EFFORT',
  HIGH_IMPACT_LOW_EFFORT = 'HIGH_IMPACT_LOW_EFFORT',
  LOW_IMPACT_HIGH_EFFORT = 'LOW_IMPACT_HIGH_EFFORT',
  LOW_IMPACT_LOW_EFFORT = 'LOW_IMPACT_LOW_EFFORT',
}
